---
  language: objective-c
  before_install:
    - gem install cocoapods -v 0.24.0
    - git submodule update --init --recursive
    - brew update
    - brew unlink xctool && brew install xctool --HEAD
  script: "rake test"